### ISSUE TITLE
Routing and Navigation

### ISSUE THREAD

**Issue by EnqiZhang99** [UCSD/webreg-mobile#7]
This is complete when the following components have been developed:

- [ ] Header Navigation with Search bar
- [ ] Bottom Navigation in Home view (Switch between Calendar, List, Final)

**Comment by ally1250** [comment]
Bottom Navigation in Home view (video):
[https://drive.google.com/file/d/1MPu06IBbdk77kogCCJ6KRM8XJhHL_GWX/view?usp=sharing](url)

Search Bar (video):
[https://drive.google.com/file/d/1thZEasSRlY6lSNwanKdPU-L9r9DoA2Xb/view?usp=sharing](url)

TODO:
1. Implement header navigation (e.g. back button)
